// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGZkYSFlhhroEL5fIPOqN__xkCD65vVU',
    appId: '1:543931891633:web:0e8ea7f0c998343ef5c790',
    messagingSenderId: '543931891633',
    projectId: 'food-delivery-7e914',
    authDomain: 'food-delivery-7e914.firebaseapp.com',
    storageBucket: 'food-delivery-7e914.firebasestorage.app',
    measurementId: 'G-TVNTCZHRTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDOiDlA3_zFokGyWZBeIXCHsufuYXDQ8',
    appId: '1:543931891633:android:a09ea4a137c2030ff5c790',
    messagingSenderId: '543931891633',
    projectId: 'food-delivery-7e914',
    storageBucket: 'food-delivery-7e914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FTMRdu_nCTwODHZJFqnHiTmVSG9JbtE',
    appId: '1:543931891633:ios:f3b19012a796bf54f5c790',
    messagingSenderId: '543931891633',
    projectId: 'food-delivery-7e914',
    storageBucket: 'food-delivery-7e914.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2FTMRdu_nCTwODHZJFqnHiTmVSG9JbtE',
    appId: '1:543931891633:ios:f3b19012a796bf54f5c790',
    messagingSenderId: '543931891633',
    projectId: 'food-delivery-7e914',
    storageBucket: 'food-delivery-7e914.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHGZkYSFlhhroEL5fIPOqN__xkCD65vVU',
    appId: '1:543931891633:web:0e8ea7f0c998343ef5c790',
    messagingSenderId: '543931891633',
    projectId: 'food-delivery-7e914',
    authDomain: 'food-delivery-7e914.firebaseapp.com',
    storageBucket: 'food-delivery-7e914.firebasestorage.app',
    measurementId: 'G-TVNTCZHRTV',
  );

}